language: python
dist: bionic
cache: pip

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: 3.8
    - python: "nightly"

script:
  - travis_wait make check coverage docs COVERAGE=coverage SPHINXAPIDOC=sphinx-apidoc

after_success:
  - |
      coverage combine
      coveralls

notifications:
  email:
    on_success: change
    on_failure: change
